name: CI-CD-Render

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # --------------------
    # Restore & Build
    # --------------------
    - name: Restore
      run: dotnet restore src/MiniSocialApp/MiniSocialApp.csproj

    - name: Build
      run: dotnet build src/MiniSocialApp/MiniSocialApp.csproj --no-restore

    # --------------------
    # Test + Coverlet
    # --------------------
    - name: Test with Coverage
      run: |
        dotnet test tests/MiniSocialApp.Tests/MiniSocialApp.Tests.csproj \
        /p:CollectCoverage=true \
        /p:CoverletOutputFormat=opencover \
        /p:CoverletOutput=./coverage/

    # --------------------
    # SonarCloud
    # --------------------
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # --------------------
    # Upload Artifacts
    # --------------------
    - name: Upload Coverage Artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ./coverage

    # --------------------
    # Docker â†’ GHCR
    # --------------------
    - name: Login to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Set image name
      run: |
        echo "IMAGE_NAME=ghcr.io/$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')/mini-social-app:latest" >> $GITHUB_ENV
        # --------------------
# Deploy to DEV
# --------------------
- name: Deploy to DEV (Render)
  if: github.ref == 'refs/heads/develop'
  run: curl -X POST ${{ secrets.RENDER_DEPLOY_DEV }}

# --------------------
# Deploy to QA
# --------------------
- name: Deploy to QA (Render)
  if: github.ref == 'refs/heads/qa'
  run: curl -X POST ${{ secrets.RENDER_DEPLOY_QA }}

# --------------------
# Deploy to PROD
# --------------------
- name: Deploy to PROD (Render)
  if: github.ref == 'refs/heads/main'
  run: curl -X POST ${{ secrets.RENDER_DEPLOY_PROD }}


    - name: Build Docker image
      run: docker build -t $IMAGE_NAME .

    - name: Push Docker image
      run: docker push $IMAGE_NAME

    # --------------------
    # Deploy to Render
    # --------------------
    - name: Trigger Render Deployment
      run: |
        curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"

