name: CI-CD-Render

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # --------------------
    # Restore & Build
    # --------------------
    - name: Restore
      run: dotnet restore src/MiniSocialApp/MiniSocialApp.csproj

    - name: Build
      run: dotnet build src/MiniSocialApp/MiniSocialApp.csproj --no-restore

    # --------------------
    # Test + Coverlet
    # --------------------
    - name: Test with Coverage
      run: |
        dotnet test tests/MiniSocialApp.Tests/MiniSocialApp.Tests.csproj \
        /p:CollectCoverage=true \
        /p:CoverletOutputFormat=opencover \
        /p:CoverletOutput=./coverage/

    # --------------------
    # SonarCloud
    # --------------------
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # --------------------
    # Upload Artifacts
    # --------------------
    - name: Upload Coverage Artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ./coverage

    # --------------------
    # Docker â†’ GHCR
    # --------------------
    - name: Login to GHCR
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

    - name: Build Docker Image
      run: docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/mini-social-app:latest .

    - name: Push Docker Image
      run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/mini-social-app:latest

    # --------------------
    # Deploy to Render
    # --------------------
    - name: Trigger Render Deployment
      run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
